### ISSUE TITLE
Failed to execute warmReset via REST

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#566] opened 2016-09-12 09:49 UTC
### Problem
On palmetto master branch (fe0d5d3), it gets error on OpenBMC to execute `warmReset()` via RESET.
os-release:
```bash
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.0-29"
VERSION_ID="v1.99.0-29-gfe0d5d3-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.0-29"
BUILD_ID="v1.99.0"
```

### How to reproduce
* From a PC, login via REST
* On the PC, execute `warmReset`, it looks OK:
```bash
$curl -b cjar -k -H "Content-Type: application/json" -X POST -d '{"data": []}' https://192.168.0.60/org/openbmc/control/bmc0/action/warmReset
{
  "data": null,
  "message": "200 OK",
  "status": "ok"
}
```
* However, BMC does not reboot, check log on BMC with `journalctl | tail`, below error log occurs:
```bash
Sep 12 09:35:53 palmetto control_bmc.exe[677]: warmReset() error: Failed to read enough data from child pid pipe (No child processes)
```

### Impacts
It does not only impact the `warmReset()` REST API, but also `prepareForUpdate` as well, because as the last step of `prepareForUpdate`, it invokes `warmReset()` as well

**Comment by williamspatrick** [comment] 2016-09-12 11:07
Duplicate of #519

**Closed by williamspatrick** 2016-09-12 11:07 UTC
