### ISSUE TITLE
Implement Field Mode

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#1653] opened 2017-05-24 01:49 UTC
Provide a way to set the BMC into Field Mode which would clear the contents of /usr/local/ (where patches can be located) for example.

**Comment by mtritz** [comment] 2017-06-15 15:20
- [ ] Create a new dbus object for setting the BMC into field mode
- [ ] When the object is called, clear the contents of /usr/local/

**Comment by mtritz** [comment] 2017-07-26 21:15
Looks like a duplicate of https://github.com/openbmc/openbmc/issues/1350 - putting task list over there.

**Comment by bradbishop** [comment] 2017-07-27 18:26
closed.  dup of #1350.

**Closed** 2017-07-27 18:25 UTC
Labels: Phase 5
