### ISSUE TITLE
Preserve MAC address on Witherspoon

### ISSUE THREAD

**Issue by anoo1** [openbmc/openbmc#525] opened 2016-08-24 21:09 UTC
Barreleye has a board VPD connected to the BMC where the MAC address is stored, so the BMC can currently read the MAC stored in the VPD and restore its value if the u-boot value gets cleared or doesn't match (like on a BMC replacement).

Witherspoon doesn't have a board VPD connected, so need to determine an alternate way to preserve the MAC (and UUID) like Barreleye does.

**Comment by williamspatrick** [comment] 2017-05-31 19:41
Suspect this is a dupe of #1315?

**Comment by rfrandse** [comment] 2017-06-07 14:25
closing as a dup

**Closed by rfrandse** 2017-06-07 14:25 UTC
Labels: Phase 5
