### ISSUE TITLE
[Witherspoon - v1.99.0-321-gb4f5019 ] PNOR update Failed

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#880] opened 2016-12-13 16:05 UTC
`root@witherspoon:~# cat /etc/version`
`20161212180427`

```
root@witherspoon:~# journalctl --no-pager | grep flash_bios.exe
Dec 12 18:06:00 witherspoon flash_bios.exe[774]: Starting flasher: bios,,/org/openbmc/control/flash/bios,
Dec 12 18:06:00 witherspoon flash_bios.exe[774]: flasher: , BMC = 1, address = 0x0
Dec 12 18:06:00 witherspoon flash_bios.exe[774]: Setting up flash
Dec 12 18:06:00 witherspoon flash_bios.exe[774]: Starting flasher: bios,,/org/openbmc/control/flash/bios,
Dec 12 18:06:01 witherspoon flash_bios.exe[774]: flasher: , BMC = 1, address = 0x0
Dec 12 18:06:01 witherspoon flash_bios.exe[774]: Setting up flash
Dec 12 18:10:19 witherspoon flash_bios.exe[774]: Starting flasher: bios,/tmp/witherspoon.pnor,/org/openbmc/control/flash/bios,
Dec 12 18:10:19 witherspoon flash_bios.exe[774]: flasher: /tmp/witherspoon.pnor, BMC = 1, address = 0x0
Dec 12 18:10:19 witherspoon flash_bios.exe[774]: Setting up flash
Dec 12 18:10:19 witherspoon flash_bios.exe[774]: Erasing... (may take a while !) Error -1 erasing chip
```

- [x] Journal log here : 
[witherspoon_pnor_update.txt](https://github.com/openbmc/openbmc/files/649414/witherspoon_pnor_update.txt)

**Comment by spinler** [comment] 2016-12-13 16:17
Same signature as https://github.com/openbmc/openbmc/issues/848

**Comment by shenki** [comment] 2016-12-15 03:00
@gkeishin please put the output of `/etc/os-version` in your report instead.

Closing as a duplicate of #848

**Closed by shenki** 2016-12-15 03:00 UTC

**Comment by gkeishin** [comment] 2016-12-15 05:21
@shenki  In general,  isn't the v1.99.0-321-gb4f5019  mentioned in the title the only needed for the version information if we are looking at /etc/os-version ?

**Comment by shenki** [comment] 2016-12-15 05:25
Yes. You're right, I didn't notice the title. Thanks for pointing that out :)
