### ISSUE TITLE
IPMI LAN cmd parameters - Destinations related

### ISSUE THREAD

**Issue by williamli80** [openbmc/openbmc#690] opened 2016-10-22 04:57 UTC
IPMI LAN Command Parameter                                          Number
Number of Destinations( Read Only )                                 17
Destination Type (volatile / non-volatile – see description ) 18
Destination Address                                                                 19

Refers to #444

**Comment by williamspatrick** [comment] 2017-05-31 19:59
Closing as duplicate of #685.

**Closed by williamspatrick** 2017-05-31 19:59 UTC
Labels: Phase 5
