### ISSUE TITLE
ObjectMapper Call failed: The resource is not found

### ISSUE THREAD

**Issue by renweihang** [openbmc/openbmc#3952] opened 2023-09-02 03:10 UTC
1. There is a normal DBus , and the corresponding path and interface can be viewed using `busctl introspect` command, but why does "ObjectMapper GetObject " indicate failure?
2. Why is it that after restarting the ObjectMapper service, "ObjectMapper GetObjec" can successfully retrieve the DBus information?

    Thank you very much!  Here are the detailed information:
```
root@g50:~# busctl introspect xyz.openbmc_project.CPLDManager /xyz/openbmc_project/inventory/item/psu/psu1 xyz.openbmc_project.Inventory.Item
NAME                               TYPE      SIGNATURE RESULT/VALUE FLAGS
.Hotplug                           property  b         false        emits-change
.Present                           property  b         true         emits-change
root@g50:~# 
root@g50:~# busctl call xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetObject sas /xyz/openbmc_project/inventory/item/psu/psu1 1 xyz.openbmc_project.Inventory.Item
Call failed: The resource is not found.
root@g50:~# 
root@g50:~# systemctl restart xyz.openbmc_project.ObjectMapper
root@g50:~# 
root@g50:~# busctl call xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper GetObject sas /xyz/openbmc_project/inventory/item/psu/psu1 1 xyz.openbmc_project.Inventory.Item
a{sas} 1 "xyz.openbmc_project.CPLDManager" 4 "org.freedesktop.DBus.Introspectable" "org.freedesktop.DBus.Peer" "org.freedesktop.DBus.Properties" "xyz.openbmc_project.Inventory.Item"
root@g50:~#
```

**Comment by mine260309** [comment] 2023-09-02 06:11
On Sat, Sep 2, 2023 at 11:10 AM renwh ***@***.***> wrote:
>
> There is a normal DBus , and the corresponding path and interface can be viewed using busctl introspect command, but why does "ObjectMapper GetObject " indicate failure?
>
> Why is it that after restarting the ObjectMapper service, "ObjectMapper GetObjec" can successfully retrieve the DBus information?

Usually this indicates an issue in the service code that the signals
like interfacesAdded/Removed are not correctly emitted, so you get an
inconsistency between DBus and mapper.
Restarting mapper makes a full introspection of the DBus and you get
the consistency back.

**Comment by williamspatrick** [comment] 2023-09-02 10:56
This is a support question, not a bug. The question is about non-upstreamed code. Closing.

**Closed by williamspatrick** 2023-09-02 10:56 UTC
