### ISSUE TITLE
OpenBMC GUI - Not able to select low priority option in event log page

### ISSUE THREAD

**Issue by samahaba** [openbmc/openbmc#2746] opened 2017-12-28 12:41 UTC
![notable to select low priority option in event log](https://user-images.githubusercontent.com/29222610/34411080-7f219f18-ebfa-11e7-96ea-f11d91e401ad.png)

**Comment by samahaba** [comment] 2017-12-28 12:47
Step to reproduce the problem:
------------------------------------

1 Go to "Server health" main menu -> "Event log" sub menu
2. Under "FILTER BY SEVERITY" click on option button "All", "High", "Medium", and then "Low" respectively and as result of this not able to select "Low" option

**Comment by iftekharuli** [comment] 2018-02-01 15:12
@samahaba If you select High. medium and then trying to select Low we automatically select ALL since High, medium and Low means all the events. Let me know if any questions.

**Comment by iftekharuli** [comment] 2018-03-15 15:42
@samahaba this is similar to https://github.com/openbmc/openbmc/issues/2750 .. I have replied in detail about the behavior. Let me know if you need more info

**Comment by gtmills** [comment] 2018-03-15 16:08
The GUI was designed this way. Closing this issue.

**Closed by gtmills** 2018-03-15 16:08 UTC
Labels: GUI
