### ISSUE TITLE
GUI: User password failed to change and no confirmation text / rejection text

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2969] opened 2018-03-05 15:13 UTC
<cde:info> SW419742 </cde:info>

**Comment by gtmills** [comment] 2018-03-05 15:18
Looks like there is no code underneath to actually do the password change. "Save change" on the Manage user account doesn't call anything. https://github.com/openbmc/phosphor-webui/blob/master/app/users/controllers/user-accounts-controller.html#L38

**Comment by gtmills** [comment] 2018-03-05 15:19
users/manage-accounts is the page

**Comment by gtmills** [comment] 2018-03-05 15:22
Command to change the password is 
```curl -c cjar -b cjar -k -H "Content-Type: application/json" -d "{\"data\": [\"abc123\"] }" -X POST  https://${bmc}/xyz/openbmc_project/user/root/action/SetPassword```

**Comment by iftekharuli** [comment] 2018-03-14 16:28
This is a duplicate of the know issue https://github.com/openbmc/openbmc/issues/2741 
We did not code this part due to the lack of the completion rest command when we handed off the GUI.

**Comment by rfrandse** [comment] 2018-03-20 15:52
<https://gerrit.openbmc-project.xyz/9610> Display error and success text
Resolves  #2969 GUI: User password failed to change and no confirmation text / rejection text

**Comment by gtmills** [comment] 2018-03-20 17:57
![success_password_change](https://user-images.githubusercontent.com/5455127/37673438-316656fe-2c3e-11e8-8af3-f17e6461543e.PNG)
Successful password change

![old_password_error](https://user-images.githubusercontent.com/5455127/37673458-3e078338-2c3e-11e8-817d-e20230447e42.PNG)

error during password change

**Closed** 2018-03-23 19:57 UTC
Labels: GUI, bug, prio_medium
