### ISSUE TITLE
IPMI LAN cmd parameters - Gateway related

### ISSUE THREAD

**Issue by williamli80** [openbmc/openbmc#688] opened 2016-10-22 04:53 UTC
IPMI LAN Command Parameter  Number
Default Gateway MAC Address         13
Backup Gateway Address                  14
Backup Gateway MAC Address         15

Refers to #444

**Comment by williamspatrick** [comment] 2017-05-31 19:59
Closing as duplicate of #685.

**Closed by williamspatrick** 2017-05-31 19:59 UTC
Labels: Phase 5
