### ISSUE TITLE
IPMI LAN cmd parameters - ARP(optional)

### ISSUE THREAD

**Issue by williamli80** [openbmc/openbmc#687] opened 2016-10-22 04:46 UTC
IPMI LAN Command Parameter          Number
BMC-generated ARP control (optional)    10
Gratuitous ARP interval (optional)          11

Refers to #444

**Comment by williamspatrick** [comment] 2017-05-31 19:59
Closing as duplicate of #685.

**Closed by williamspatrick** 2017-05-31 19:59 UTC
Labels: Phase 5
