### ISSUE TITLE
IPMI LAN cmd parameters - Dynamic Router Info

### ISSUE THREAD

**Issue by williamli80** [openbmc/openbmc#692] opened 2016-10-22 05:20 UTC
IPMI LAN Command Parameter  Number
Number of Dynamic Router Info Sets  73
IPv6 Dynamic Router Info IP Address 74
IPv6 Dynamic Router Info MAC Address    75
IPv6 Dynamic Router Info Prefix Length  76
IPv6 Dynamic Router Info Prefix Value   77
IPv6 Dynamic Router Received Hop Limit  78
IPv6 Neighbor Discovery / SLAAC Timing Configuration Support    79
IPv6 Neighbor Discovery / SLAAC Timing Configuration    80

Refers to #444

**Comment by williamspatrick** [comment] 2017-05-31 19:59
Closing as duplicate of #685.

**Closed by williamspatrick** 2017-05-31 19:59 UTC
Labels: Phase 5
