### ISSUE TITLE
IPMI services taking too much time to exit on BMC reboot

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3465] opened 2019-01-17 07:47 UTC
While rebooting BMC, all services are expected to exit cleanly, and systemd will wait for services to exit.

Both host ipmid and net-ipmid take too much time to exit, we see logs like below from serial console:
```
[  OK  ] Stopped Phosphor Inband IPMI.
         Stopping Phosphor IPMI BT DBus Bridge...
[  OK  ] Stopped Clear one time boot overrides.
[  OK  ] Stopped Phosphor IPMI BT DBus Bridge.
[*     ] A stop job is running for Network IPMI daemon (1min 18s / 1min 30s)
```

Host ipmid takes about 30 seconds to stop, and net ipmid eventually times out.
So it affects BMC reboot time by about 90 seconds.

This issue happens on both Palmetto and Romulus with latest OpenBMC (e.g. cea235afb), and have been there for a while.

Note: this issue is created here because I do not know if it should be created at host ipmid or net ipmid repo.
If we have figured out the root cause, it may be moved to related repo.

**Comment by nest1ing** [comment] 2019-01-17 08:52
This issue happens on Vesnin too.

**Comment by gkeishin** [comment] 2019-01-22 04:32
Yeah, I have noticed it to in recent Master code when resetting BMC.

**Comment by edtanous** [comment] 2019-01-23 06:54
Our validation team has noticed this as well.  Unclear as to the root cause at this point.

**Comment by geissonator** [comment] 2019-01-25 19:33
Related to issue that zerotierone hit with new systemd? https://github.com/zerotier/ZeroTierOne/issues/738

**Comment by geissonator** [comment] 2019-02-05 01:55
This continues to add an extra minute to all of our HW CI runs :(

**Comment by vmauery** [comment] 2019-02-06 00:10
Autobump https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/17891 should have fixed this.

**Comment by nest1ing** [comment] 2019-02-07 09:42
On VESNIN I see now things like this:
```
[  OK  ] Removed slice system-org.openbmc.control.Power.slice.
         Stopping Network Service...
[  OK  ] Stopped Network Service.
[   ***] A stop job is running for Phosphor Inband IPMI (17s / 1min 30s)
```
It lasts about 30 seconds.

**Comment by mine260309** [comment] 2019-02-11 02:04
> On VESNIN I see now things like this:
> 
> ```
> [  OK  ] Removed slice system-org.openbmc.control.Power.slice.
>          Stopping Network Service...
> [  OK  ] Stopped Network Service.
> [   ***] A stop job is running for Phosphor Inband IPMI (17s / 1min 30s)
> ```
> It lasts about 30 seconds.

The same on Romulus as well.
Inband IPMI takes about 30s, and network ipmid takes about 1min 30s.

**Comment by mine260309** [comment] 2019-03-14 02:47
With OpenBMC e7428cb, the net-ipmid seems OK, but inband ipmid still takes about 30s to exit.

@vmauery Could you help to check inband ipmid as well?
And could you share which commit in net ipmid fixes the issue? Should the same fix apply to inband ipmid?

**Comment by amboar** [comment] 2019-03-20 03:11
phosphor-host-ipmid taking 30s to terminate is likely because openpower-host-ipmi-flash is blocking SIGTERM until the host timeout expires. At that point it should unblock SIGTERM, which will cause ipmid to then cleanly shut down.

**Comment by geissonator** [comment] 2019-03-26 20:17
Is this something you'll be able to optimize @amboar ?  Still seeing it in the 2.7.0-dev-170-g8f73848 level of code (all the latest ipmi and hiomap changes).  I see it hitting the max 1min 36s too, not 30s.

**Comment by amboar** [comment] 2019-03-27 23:15
So I don't know where 1min 36s comes from; it's possible that ipmid is not unblocking sigterm. @anoo1 has been working with this to get the phosphor-host-ipmi refactor in, so she'd be the best person to ask at this point. As for optimising, if ipmid is aware of the host state then we could avoid sending the SEL and thus avoid the timeout.

**Comment by gkeishin** [comment] 2019-04-16 14:14
Did a trial here to see whats going out there.. 

```
/etc/systemd/journald.conf
ForwardToConsole=yes 
```
rebooted BMC and I see this where the reboot was taking time .. it taking time spending shutting down the host services
```
[  OK  ] Stopped Network Service.
[    **] A stop job is running for Phosphor Inband IPMI (36s / 1min 44s)
[  248.991147] ipmid[1429]: Host control timeout hit!
[**    ] A stop job is running for Phosphor Inband IPMI (1min 44s / 1min 44s)
[***   ] A stop job is running for Phosphor Inband IPMI (1min 44s / 3min 14s)
[  317.004216] systemd[1]: phosphor-ipmi-host.service: Killing process 1429 (ipmid) with signal SIGKILL.
[  317.081965] systemd[1]: phosphor-ipmi-host.service: Main process exited, code=killed, status=9/KILL
[  OK  ] Stopped Phosphor Inband IPMI.
```

**Comment by anoo1** [comment] 2019-04-16 21:19
Pushed out a fix: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-host-ipmi-flash/+/20671

Tested killing the ipmi service but need to verify the reboot path. Will do that tomorrow.

**Comment by amboar** [comment] 2019-04-17 04:30
Oh, I saw the patch and didn't see the comment about testing the reboot path. I've merged it as is, lets do a follow up patch if necessary.

**Closed** 2019-04-17 04:29 UTC

**Comment by anoo1** [comment] 2019-04-17 14:43
Thanks Andrew, George and I have checked the reboot path is not delayed anymore with the merged patch.
