### ISSUE TITLE
Setting networks to DHCP from Petiteboot, isn't preserved when Witherspoon is rebooted

### ISSUE THREAD

**Issue by moralesj** [openbmc/openbmc#2087] opened 2017-08-03 19:18 UTC
Trying to provision a Witherspoon, using xCat.  Petiteboot is showing a network interface with a static IP address.  

Networks are set back to DHCP using Petiteboot System Menu, and selecting DHCP for all devices., and then selecting OK.  When the system is rebooted, and the networks are check in Petiteboot, the devices show that they have reverted back to having a static IP, which is incorrect.

**Comment by sammj** [comment] 2017-08-03 23:19
This is a duplicate of https://github.com/openbmc/openbmc/issues/2033

**Comment by ratagupt** [comment] 2017-08-04 04:04
I am not sure it is a duplicate to 2033
I need below info.
1) What was the ipmi command which you ran?
2) Did you verify that network settings get applied on openbmc?
3) I assume that as ipmitool doesn't throw error,so it gets you a feeling that changes successfully applied.
For me that could be a settings validation issue.

**Comment by sammj** [comment] 2017-08-04 04:07
> Networks are set back to DHCP using Petiteboot System Menu, and selecting DHCP for all devices., and then selecting OK. When the system is rebooted, and the networks are check in Petiteboot, the devices show that they have reverted back to having a static IP, which is incorrect.

What Static IP is set? If it is `0.0.0.0`, then it will be a dupe of https://github.com/openbmc/openbmc/issues/2033

**Comment by ratagupt** [comment] 2017-08-04 04:08
no,it can't be set as settings validation doesn't allow that.

**Comment by sammj** [comment] 2017-08-04 04:09
@ratagupt Except as seen in https://github.com/openbmc/openbmc/issues/2033 that address _is_ getting set, because that's the default IP value in the OpenBMC code.

**Comment by ratagupt** [comment] 2017-08-04 04:37
yes.

**Comment by ratagupt** [comment] 2017-08-04 04:37
The below command works fine.

**Comment by dkodihal** [comment] 2017-08-04 08:01
I have a couple of fixes in the settings app that will definitely be required to solve this bug, but at the moment I don't know if networkd or host-ipmid needs changes as well. @ratagupt to confirm.

Here are my fixes (they're up for code review) :

https://gerrit.openbmc-project.xyz/#/c/5775/
https://gerrit.openbmc-project.xyz/#/c/5776/

**Comment by ratagupt** [comment] 2017-08-04 13:00
I am also hoping with these fixes,the issue should be fixed.
Let submitter to respond back my querys.

**Comment by ralphbellofatto** [comment] 2017-08-04 17:02
When can we expect to see a firmware update that includes this and when will it be incorporated in new witherspoon systems?

**Comment by dkodihal** [comment] 2017-08-08 16:43
This should be fixed in https://github.com/openbmc/openbmc/commit/201bd626032b334d1fee213be4272c1155662ae8.

**Closed by dkodihal** 2017-08-08 16:43 UTC
Labels: bug, Phase 5, prio_high
