### ISSUE TITLE
STC:OP910:Witherspoon:OS reboot request leaves system in powered off state

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2382] opened 2017-09-27 21:08 UTC
<cde:info> SW403240 </cde:info>

**Comment by cbostic** [comment] 2017-09-28 02:19
```==== State: Open by: tdylla on 26 September 2017 12:35:14 ==== 1

System - yl13ub

BMC - yl13ubbmc.rch.stglabs.ibm.com (9.5.166.120)   root/0penBmc
OS  - yl13ubos.rch.stglabs.ibm.com  (9.5.166.121)   root/C0vfefed or root/Why4askme
OS Console Connect Instrutions:
1. ssh to bmc port 2200
2. signon with bmc userid & password
3. press enter and you should now be on OS console.  If system is at mon you can use ? to get control and help.


Firmware Code Levels
====================
root@witherspoon:~# cat /var/lib/phosphor-software-manager/pnor/ro/VERSION
IBM-witherspoon-redbud-ibm-OP9_v1.19_1.33
        op-build-450d9d7
        buildroot-2017.08-6-g319c6e1
        skiboot-v5.8-73-g4a2b8317fd3f-p6faaa2d
        hostboot-3d6c541
        linux-4.13-openpower1-pe8fb223
        petitboot-v1.5.1-p36336db
        machine-xml-f8aaa73-p5482dba
        occ-a43395b
        hostboot-binaries-836385d
        capp-ucode-9c73e9f
        sbe-8d90ab2
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v1.99.10"
VERSION_ID="ibm-v1.99.10-0-r7-0-gcce0f1b"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v1.99.10"
BUILD_ID="ibm-v1.99.10-0-r7"


BMC State
=========
root@witherspoon:~# obmcutil power
pgood = 1
state = 1
pgood_timeout = 10
root@witherspoon:~# obmcutil state
CurrentBMCState:    xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState:  xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState:   xyz.openbmc_project.State.Host.HostState.Off


Problem Description:
====================
I removed A/C power from the system and then reapplied A/C power and powered the system on from the BMC with the obmcutil poweron command.  The system to the OS.  After running htx for a short time, the system was rebooted.  The system appeared to terminate normally in the os but never powered back up.  I check the BMC state of the power and States they appear to be in conflict with each other.

System is sitting in the failed state and being held.  Please connect to system and collect the debug information you need to correct the issue.  BMC dmesg output is below.


BMC DMESG OUTPUT
================

root@witherspoon:~# dmesg
[ 4544.650000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4544.650000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4544.710000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4544.710000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4544.710000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4544.710000] [<8023d98c>] (device_for_each_child) from [<802ce03c>] (master_rescan_store+0x28/0x40)
[ 4544.710000] [<802ce03c>] (master_rescan_store) from [<8023c310>] (dev_attr_store+0x28/0x34)
[ 4544.710000] [<8023c310>] (dev_attr_store) from [<8014541c>] (sysfs_kf_write+0x50/0x54)
[ 4544.710000] [<8014541c>] (sysfs_kf_write) from [<80144b14>] (kernfs_fop_write+0xe4/0x1e4)
[ 4544.710000] [<80144b14>] (kernfs_fop_write) from [<800e24b4>] (__vfs_write+0x3c/0x128)
[ 4544.780000] [<800e24b4>] (__vfs_write) from [<800e2730>] (vfs_write+0xb0/0x178)
[ 4544.780000] [<800e2730>] (vfs_write) from [<800e28e4>] (SyS_write+0x4c/0xa0)
[ 4544.790000] [<800e28e4>] (SyS_write) from [<8000a540>] (ret_fast_syscall+0x0/0x34)
[ 4667.360000] INFO: task sh:2036 blocked for more than 120 seconds.
[ 4667.360000]       Tainted: G        W       4.10.17-c4227b43277bbd0992d10d764d4958239786503d #1
[ 4667.370000] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4667.370000] sh              D    0  2036      1 0x00000000
[ 4667.370000] [<803ff444>] (__schedule) from [<803ff774>] (schedule+0x54/0xac)
[ 4667.390000] [<803ff774>] (schedule) from [<80402b64>] (schedule_timeout+0x260/0x34c)
[ 4667.390000] [<80402b64>] (schedule_timeout) from [<80400260>] (wait_for_common+0x8c/0x12c)
[ 4667.390000] [<80400260>] (wait_for_common) from [<8040040c>] (wait_for_completion+0x20/0x24)
[ 4667.390000] [<8040040c>] (wait_for_completion) from [<802d5940>] (i2c_del_adapter+0x1d0/0x270)
[ 4667.420000] [<802d5940>] (i2c_del_adapter) from [<802d9bc4>] (fsi_i2c_remove+0x3c/0x50)
[ 4667.420000] [<802d9bc4>] (fsi_i2c_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 4667.420000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 4667.420000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 4667.460000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 4667.460000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4667.460000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4667.460000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4667.460000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4667.510000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4667.520000] [<8023d98c>] (device_for_each_child) from [<802ce3f8>] (fsi_master_unregister+0x44/0x58)
[ 4667.520000] [<802ce3f8>] (fsi_master_unregister) from [<802ce480>] (hub_master_remove+0x20/0x3c)
[ 4667.530000] [<802ce480>] (hub_master_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 4667.530000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 4667.530000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 4667.560000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 4667.570000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4667.570000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4667.590000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4667.590000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4667.590000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4667.620000] [<8023d98c>] (device_for_each_child) from [<802ce03c>] (master_rescan_store+0x28/0x40)
[ 4667.620000] [<802ce03c>] (master_rescan_store) from [<8023c310>] (dev_attr_store+0x28/0x34)
[ 4667.620000] [<8023c310>] (dev_attr_store) from [<8014541c>] (sysfs_kf_write+0x50/0x54)
[ 4667.620000] [<8014541c>] (sysfs_kf_write) from [<80144b14>] (kernfs_fop_write+0xe4/0x1e4)
[ 4667.620000] [<80144b14>] (kernfs_fop_write) from [<800e24b4>] (__vfs_write+0x3c/0x128)
[ 4667.660000] [<800e24b4>] (__vfs_write) from [<800e2730>] (vfs_write+0xb0/0x178)
[ 4667.660000] [<800e2730>] (vfs_write) from [<800e28e4>] (SyS_write+0x4c/0xa0)
[ 4667.660000] [<800e28e4>] (SyS_write) from [<8000a540>] (ret_fast_syscall+0x0/0x34)
[ 4790.240000] INFO: task sh:2036 blocked for more than 120 seconds.
[ 4790.240000]       Tainted: G        W       4.10.17-c4227b43277bbd0992d10d764d4958239786503d #1
[ 4790.240000] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4790.260000] sh              D    0  2036      1 0x00000000
[ 4790.260000] [<803ff444>] (__schedule) from [<803ff774>] (schedule+0x54/0xac)
[ 4790.260000] [<803ff774>] (schedule) from [<80402b64>] (schedule_timeout+0x260/0x34c)
[ 4790.260000] [<80402b64>] (schedule_timeout) from [<80400260>] (wait_for_common+0x8c/0x12c)
[ 4790.260000] [<80400260>] (wait_for_common) from [<8040040c>] (wait_for_completion+0x20/0x24)
[ 4790.300000] [<8040040c>] (wait_for_completion) from [<802d5940>] (i2c_del_adapter+0x1d0/0x270)
[ 4790.300000] [<802d5940>] (i2c_del_adapter) from [<802d9bc4>] (fsi_i2c_remove+0x3c/0x50)
[ 4790.310000] [<802d9bc4>] (fsi_i2c_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 4790.320000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 4790.320000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 4790.340000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 4790.340000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4790.340000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4790.370000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4790.370000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4790.370000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4790.370000] [<8023d98c>] (device_for_each_child) from [<802ce3f8>] (fsi_master_unregister+0x44/0x58)
[ 4790.400000] [<802ce3f8>] (fsi_master_unregister) from [<802ce480>] (hub_master_remove+0x20/0x3c)
[ 4790.400000] [<802ce480>] (hub_master_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 4790.400000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 4790.400000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 4790.400000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 4790.450000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4790.460000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4790.470000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4790.480000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4790.480000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4790.500000] [<8023d98c>] (device_for_each_child) from [<802ce03c>] (master_rescan_store+0x28/0x40)
[ 4790.500000] [<802ce03c>] (master_rescan_store) from [<8023c310>] (dev_attr_store+0x28/0x34)
[ 4790.510000] [<8023c310>] (dev_attr_store) from [<8014541c>] (sysfs_kf_write+0x50/0x54)
[ 4790.510000] [<8014541c>] (sysfs_kf_write) from [<80144b14>] (kernfs_fop_write+0xe4/0x1e4)
[ 4790.510000] [<80144b14>] (kernfs_fop_write) from [<800e24b4>] (__vfs_write+0x3c/0x128)
[ 4790.540000] [<800e24b4>] (__vfs_write) from [<800e2730>] (vfs_write+0xb0/0x178)
[ 4790.540000] [<800e2730>] (vfs_write) from [<800e28e4>] (SyS_write+0x4c/0xa0)
[ 4790.550000] [<800e28e4>] (SyS_write) from [<8000a540>] (ret_fast_syscall+0x0/0x34)
[ 4913.120000] INFO: task sh:2036 blocked for more than 120 seconds.
[ 4913.120000]       Tainted: G        W       4.10.17-c4227b43277bbd0992d10d764d4958239786503d #1
[ 4913.120000] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 4913.120000] sh              D    0  2036      1 0x00000000
[ 4913.120000] [<803ff444>] (__schedule) from [<803ff774>] (schedule+0x54/0xac)
[ 4913.120000] [<803ff774>] (schedule) from [<80402b64>] (schedule_timeout+0x260/0x34c)
[ 4913.120000] [<80402b64>] (schedule_timeout) from [<80400260>] (wait_for_common+0x8c/0x12c)
[ 4913.120000] [<80400260>] (wait_for_common) from [<8040040c>] (wait_for_completion+0x20/0x24)
[ 4913.120000] [<8040040c>] (wait_for_completion) from [<802d5940>] (i2c_del_adapter+0x1d0/0x270)
[ 4913.180000] [<802d5940>] (i2c_del_adapter) from [<802d9bc4>] (fsi_i2c_remove+0x3c/0x50)
[ 4913.180000] [<802d9bc4>] (fsi_i2c_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 4913.180000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 4913.180000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 4913.180000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 4913.180000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4913.180000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4913.180000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4913.260000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4913.260000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4913.260000] [<8023d98c>] (device_for_each_child) from [<802ce3f8>] (fsi_master_unregister+0x44/0x58)
[ 4913.260000] [<802ce3f8>] (fsi_master_unregister) from [<802ce480>] (hub_master_remove+0x20/0x3c)
[ 4913.260000] [<802ce480>] (hub_master_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 4913.260000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 4913.260000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 4913.260000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 4913.260000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 4913.340000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 4913.340000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4913.340000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 4913.340000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 4913.340000] [<8023d98c>] (device_for_each_child) from [<802ce03c>] (master_rescan_store+0x28/0x40)
[ 4913.340000] [<802ce03c>] (master_rescan_store) from [<8023c310>] (dev_attr_store+0x28/0x34)
[ 4913.340000] [<8023c310>] (dev_attr_store) from [<8014541c>] (sysfs_kf_write+0x50/0x54)
[ 4913.340000] [<8014541c>] (sysfs_kf_write) from [<80144b14>] (kernfs_fop_write+0xe4/0x1e4)
[ 4913.340000] [<80144b14>] (kernfs_fop_write) from [<800e24b4>] (__vfs_write+0x3c/0x128)
[ 4913.340000] [<800e24b4>] (__vfs_write) from [<800e2730>] (vfs_write+0xb0/0x178)
[ 4913.340000] [<800e2730>] (vfs_write) from [<800e28e4>] (SyS_write+0x4c/0xa0)
[ 4913.430000] [<800e28e4>] (SyS_write) from [<8000a540>] (ret_fast_syscall+0x0/0x34)
[ 5036.010000] INFO: task sh:2036 blocked for more than 120 seconds.
[ 5036.010000]       Tainted: G        W       4.10.17-c4227b43277bbd0992d10d764d4958239786503d #1
[ 5036.020000] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 5036.020000] sh              D    0  2036      1 0x00000000
[ 5036.020000] [<803ff444>] (__schedule) from [<803ff774>] (schedule+0x54/0xac)
[ 5036.040000] [<803ff774>] (schedule) from [<80402b64>] (schedule_timeout+0x260/0x34c)
[ 5036.050000] [<80402b64>] (schedule_timeout) from [<80400260>] (wait_for_common+0x8c/0x12c)
[ 5036.050000] [<80400260>] (wait_for_common) from [<8040040c>] (wait_for_completion+0x20/0x24)
[ 5036.070000] [<8040040c>] (wait_for_completion) from [<802d5940>] (i2c_del_adapter+0x1d0/0x270)
[ 5036.070000] [<802d5940>] (i2c_del_adapter) from [<802d9bc4>] (fsi_i2c_remove+0x3c/0x50)
[ 5036.070000] [<802d9bc4>] (fsi_i2c_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 5036.090000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 5036.090000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 5036.090000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 5036.090000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 5036.130000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 5036.140000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 5036.150000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 5036.150000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 5036.170000] [<8023d98c>] (device_for_each_child) from [<802ce3f8>] (fsi_master_unregister+0x44/0x58)
[ 5036.170000] [<802ce3f8>] (fsi_master_unregister) from [<802ce480>] (hub_master_remove+0x20/0x3c)
[ 5036.170000] [<802ce480>] (hub_master_remove) from [<80242728>] (device_release_driver_internal+0x144/0x1d8)
[ 5036.170000] [<80242728>] (device_release_driver_internal) from [<802427dc>] (device_release_driver+0x20/0x24)
[ 5036.200000] [<802427dc>] (device_release_driver) from [<802409f8>] (bus_remove_device+0xe8/0x14c)
[ 5036.200000] [<802409f8>] (bus_remove_device) from [<8023f728>] (device_del+0x1f4/0x314)
[ 5036.200000] [<8023f728>] (device_del) from [<8023f86c>] (device_unregister+0x24/0x6c)
[ 5036.200000] [<8023f86c>] (device_unregister) from [<802cd308>] (__fsi_slave_remove_device+0x18/0x20)
[ 5036.200000] [<802cd308>] (__fsi_slave_remove_device) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 5036.250000] [<8023d98c>] (device_for_each_child) from [<802cd2dc>] (__fsi_master_remove_slave+0x24/0x38)
[ 5036.250000] [<802cd2dc>] (__fsi_master_remove_slave) from [<8023d98c>] (device_for_each_child+0x64/0x90)
[ 5036.250000] [<8023d98c>] (device_for_each_child) from [<802ce03c>] (master_rescan_store+0x28/0x40)
[ 5036.250000] [<802ce03c>] (master_rescan_store) from [<8023c310>] (dev_attr_store+0x28/0x34)
[ 5036.250000] [<8023c310>] (dev_attr_store) from [<8014541c>] (sysfs_kf_write+0x50/0x54)
[ 5036.250000] [<8014541c>] (sysfs_kf_write) from [<80144b14>] (kernfs_fop_write+0xe4/0x1e4)
[ 5036.300000] [<80144b14>] (kernfs_fop_write) from [<800e24b4>] (__vfs_write+0x3c/0x128)
[ 5036.300000] [<800e24b4>] (__vfs_write) from [<800e2730>] (vfs_write+0xb0/0x178)
[ 5036.300000] [<800e2730>] (vfs_write) from [<800e28e4>] (SyS_write+0x4c/0xa0)
[ 5036.300000] [<800e28e4>] (SyS_write) from [<8000a540>] (ret_fast_syscall+0x0/0x34)

==== State: Open by: cde00 on 26 September 2017 12:45:17 ==== 2



==== State: Open by: andrewg on 26 September 2017 12:57:37 ==== 3

#=#=# 2017-09-26 12:57:35 (CDT) #=#=#
New OwnerInfo = [Bostic, Christopher l. (cbostic@us.ibm.com)]
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#


==== State: Open by: jayeshp on 26 September 2017 16:27:54 ==== 4

dup of SW403064?


==== State: Open by: jayeshp on 26 September 2017 16:30:02 ==== 5

ignore my last comment.


==== State: Open by: jayeshp on 26 September 2017 16:30:57 ==== 6

#=#=# 2017-09-26 16:30:55 (CDT) #=#=#
New Priority = [1]
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#


==== State: Open by: justinmc on 27 September 2017 13:24:35 ==== 7

I opened SW403343 this morning which looks like it may in part be a recreate of the reboot issue in this defect.  My system yl13u8.aus.stglabs.ibm.com checkstopped, which initiated a reboot that did not succeed.  Now the system is showing

root@witherspoon:~$ obmcutil power
pgood = 1
state = 1
pgood_timeout = 10

root@witherspoon:~$ obmcutil state
CurrentBMCState:    xyz.openbmc_project.State.BMC.BMCState.Ready
CurrentPowerState:  xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState:   xyz.openbmc_project.State.Host.HostState.Off

and will not respond to poweron.  Currently holding in failed state.


==== State: Open by: rfrandse on 27 September 2017 16:03:42 ==== 8

#=#=# 2017-09-27 16:03:39 (CDT) #=#=#
New Component_Name = [openbmc_ext]
New OwnerInfo = [Bostic, Christopher l. (cbostic@us.ibm.com)]
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#


==== State: Open by: cde00 on 27 September 2017 16:08:05 ==== 9

<cde:info>The defect was bridged to https://github.com/openbmc/openbmc/issues/2382 </cde:info>
```

**Comment by cbostic** [comment] 2017-09-28 18:02
#STATUS

I've rejected SW403240 as a duplicate of SW401584.  Expecting the cde bridge to close this issue out now.

**Comment by rfrandse** [comment] 2017-09-28 19:59
Closing

**Closed by rfrandse** 2017-09-28 19:59 UTC
Labels: bug
