### ISSUE TITLE
BMC went into bad state and unable to ssh

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc#1549] opened 2017-05-03 09:53 UTC
witherspoon system went into bad state when running CT and inband ipmi was enabled while running.
During this testing BMC went into bad state where IP was pingable but we were unable ssh and even we were unable to access serial port console. To bring system into normal state we did a dediprog to get the latest 0penBMC code on flash. We dont have any logs as system was un accessible.

**Comment by prkatti1** [comment] 2017-05-03 11:37
Version Info-
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.4-82"
VERSION_ID="v1.99.4-82-g874f12e"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.4-82"
BUILD_ID="v1.99.4"

**Comment by gkeishin** [comment] 2017-05-03 13:18
Dupe of https://github.com/openbmc/openbmc/issues/1161

**Comment by anoo1** [comment] 2017-05-05 15:19
How do we know it's a dup if we have no data?
Please add the serial port output from a power cycle next time this is seen, before reflashing the system.
Reopening, you can close if this doesn't recreate.

**Comment by anoo1** [comment] 2017-05-05 15:27
Closing. Reopen if this is seen again and attached the data mentioned above.

**Closed by anoo1** 2017-05-05 15:27 UTC
