### ISSUE TITLE
Improvements in Mapper Performance

### ISSUE THREAD

**Issue by tomjoseph83** [openbmc/openbmc#2860] opened 2018-02-01 07:07 UTC

**Comment by amboar** [comment] 2018-02-04 22:56
@tomjoseph83 can you provide some information here about what the problem is and how you plan to address it? How do we know that we have a performance issue? Has anyone quantified it? What strategies do we have for improving it? When can we close this issue (i.e. what's our threshold for having "fixed" the performance issue)?

**Comment by rfrandse** [comment] 2018-09-04 18:17
moved to https://github.com/ibm-openbmc/dev/issues/153

**Closed by rfrandse** 2018-09-04 18:17 UTC
