### ISSUE TITLE
on click logout -  not happening

### ISSUE THREAD

**Issue by sivassrr** [openbmc/openbmc#2649] opened 2017-11-17 17:56 UTC
Continuation of  previous issue https://github.com/openbmc/openbmc/issues/2648

On click logout - not happening, Had to refresh and then it logs off. 

Expectation is to logoff after clicking logout button. ( Refresh should be avoided).

**Comment by iftekharuli** [comment] 2018-03-13 16:16
This has been fixed. Let me know

**Comment by amboar** [comment] 2018-03-14 06:53
@iftekharuli Please could link to the patch fixing the issue when making these comments? That way others can figure out what they need to do to get the fix.

**Comment by iftekharuli** [comment] 2018-03-21 20:49
Duplicate https://github.com/openbmc/openbmc/issues/2737 
Also link for the the fix https://gerrit.openbmc-project.xyz/#/c/8828/

**Comment by gtmills** [comment] 2018-04-19 18:36
This was a duplicate of #2737 and has been fixed with https://gerrit.openbmc-project.xyz/#/c/8828/.

**Closed by gtmills** 2018-04-19 18:36 UTC
