### ISSUE TITLE
IPL: kernel: Unable to handle kernel paging request / Internal error: Oops: 5 [#1] ARM (device_del) on wsbmc016 with 910.1742.20171011b

### ISSUE THREAD

**Issue by cdeadmin** [openbmc/openbmc#2528] opened 2017-10-27 14:18 UTC
<cde:info> SW405012 </cde:info>

**Comment by eddiejames** [comment] 2017-10-30 15:48
Frequent bad memory access when rebooting the host.

This one is due to memory corruption caused by the occ-hmwon driver. This is only present if the OCC returns some extended sensors in the poll response, which is why we haven't seen this until recently.

We already have a fix merged in the openbmc Linux kernel: https://github.com/openbmc/linux/commit/5806148a26fdea2a972d70d0c35fbf7cae000250

**Closed** 2017-10-30 23:14 UTC
Labels: bug, ibm-internal, prio_high
