### ISSUE TITLE
Add witherspoon machine to tree

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#367] opened 2016-06-15 05:43 UTC
We need to add the witherspoon board to the tree. This involves:

 * `meta-openbmc-machines/meta-openpower/meta-ibm/meta-witherspoon/`
 * skeleton `Witherspoon.py`

**Comment by williamspatrick** [comment] 2016-06-15 11:47
This is a duplicate of #296.

**Closed by williamspatrick** 2016-06-15 11:47 UTC
