### ISSUE TITLE
Is there a way to transfer files between BMC and host？

### ISSUE THREAD

**Issue by lockless** [openbmc/openbmc#3378] opened 2018-09-14 08:52 UTC
For some reason， we need transfer files between BMC and host， is there a way to do this？
Thanks for any idea !

**Comment by gtmills** [comment] 2018-09-14 18:42
Hi @lockless, this is a good question for IRC or the mailing list, as it's not a bug or feature request. You can sign yourself up for the mailing list at https://lists.ozlabs.org/listinfo/openbmc

**Comment by gtmills** [comment] 2018-10-12 22:16
Closing since not a bug or feature request and instead a question.

**Closed by gtmills** 2018-10-12 22:16 UTC
