### ISSUE TITLE
Enable x86-power-control in default openbmc image.

### ISSUE THREAD

**Issue by abirami-sekar-3** [openbmc/openbmc#3925] opened 2023-05-05 07:26 UTC
Hi @williamspatrick , @gtmills , @geissonator , 

I am adding x86-power-control to default openbmc image, i am getting **Freezing Execution error**  on booting, the details are mentioned in the comment, https://github.com/openbmc/openbmc/issues/3853#issuecomment-1517592383

In order to control host power operation, i am trying to add x86-power-control, which it is stopping on kernel boot, 
Can you please tell me how to add x86-power-control and phosphor-state-manager both in single image.

Thanks,
Abirami S

**Comment by williamspatrick** [comment] 2023-09-25 08:46
Duplicate of #3853.

**Closed by williamspatrick** 2023-09-25 08:46 UTC
