### ISSUE TITLE
IPMI LAN cmd parameters - RMCP+ introduced

### ISSUE THREAD

**Issue by williamli80** [openbmc/openbmc#691] opened 2016-10-22 05:02 UTC
IPMI LAN Command Parameter  Number
802.1q VLAN ID (12-bit) 20
802.1q VLAN Priority    21
RMCP+ Messaging Cipher Suite Entry Support( Read Only ) 22
RMCP+ Messaging Cipher Suite Entries( Read Only )   23
RMCP+ Messaging Cipher Suite Privilege Levels   24
Destination Address VLAN TAGs   25
Bad Password Threshold  26
IPv6/IPv4 Support   50
IPv6/IPv4 Addressing Enables    51
IPv6/IPv4 Header Static Traffic Class   52
IPv6 Header Static Hop Limit    53
IPv6 Header Flow Label  54
IPv6 Status 55
IPv6 Static Addresses   56
IPv6 DHCPv6 Static DUID storage length  57
IPv6 DHCPv6 Static DUIDs    58
IPv6 Dynamic ( SLAAC/DHCPv6) Address    59
IPv6 DHCPv6 Dynamic DUID storage length 60
IPv6 DHCPv6 Dynamic DUIDs   61
IPv6 DHCPv6 Timing Configuration Support    62
IPv6 DHCPv6 Timing & Configuration  63
IPv6 Router Address Configuration Control   64
IPv6 Static Router 1 IP Address  65
IPv6 Static Router 1 MAC Address    66
IPv6 Static Router 1 Prefix Length  67
IPv6 Static Router 1 Prefix Value   68
IPv6 Static Router 2 Address    69
IPv6 Static Router 2 MAC Address    70
IPv6 Static Router 2 Prefix Length  71
IPv6 Static Router 2 Prefix Value   72

Refers to #444

**Comment by williamspatrick** [comment] 2017-05-31 19:59
Closing as duplicate of #685.

**Closed by williamspatrick** 2017-05-31 19:59 UTC
Labels: Phase 5
